### ISSUE TITLE
runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by erickufrin-okta** [jpf/loghook#1]
When I run loghook I see a stream of events and then this error occurs.

nic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.(*logEventResult).Get(0xc0000b2300, 0xc0000f5a01, 0xc0001c5160)
	/Users/abc/loghook/loghook.go:141 +0x14d
main.main()
	/Users/abc/loghook/loghook.go:281 +0x39f

I am trying to make this work to collect System Log events "system.org.rate_limit.violation" or "system.org.rate_limit.warning" and trigger webhooks accordingly.

I have tried building the code from the instructions and also tried the compiled binary for osx and both had the same result. 

https://developer.okta.com/blog/2017/10/17/add-the-power-of-webhooks-to-your-app-with-oktas-system-log

**Comment by somerandow** [comment]
```go
    for {
        for logEvents.Next() {
            logEvent, raw := logEvents.Get()
            if !logEvent.Published.IsZero() {
                logEvents.Since = logEvent.Published.Add(time.Second * 1)
            }
            eventProcessor.Process(logEvent, raw)
        }
        if logEvents.err != nil {
            log.Warning("Error:", logEvents.err)
            break
        }
        logEvents.Sleep()
    }
```
Try 
```go
        for logEvents.Next() {
            logEvent, raw := logEvents.Get()
            if !logEvent.Published.IsZero() {
                logEvents.Since = logEvent.Published.Add(time.Second * 1)
            }
            eventProcessor.Process(logEvent, raw)
            logEvents.Sleep()
            if logEvents.err != nil {
            log.Warning("Error:", logEvents.err)
            break
        }
        }
        
```

**Comment by erickufrin-okta** [comment]
@seanmalloy thank you!

**Comment by seanmalloy** [comment]
@erickufrin I'll try to take a look at this. My rough ETA is probably a few days.
